[target.riscv32imc-unknown-none-elf]
runner = "espflash --monitor --speed 921600"

[build]
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "link-arg=-Trom_functions.x",

  "-C", "force-frame-pointers",
]
target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]
